export const HRRoutes = {
  //++++++++++ Resources Routes
  hrDepartments: "/departments",
  humanrescourcesDashboard: "/humanrescourcesDashboard",
  employees: "/employees",
  departments: "/departments",
  applicants: "/applicants",
  singleEmployee: "/singleEmployee/:id",
  setupHR: "/setupHR",
  appilicants: "/appilicants",
  payrollManagement: "/payrollManagement",
  singlePayrollManagement: "/payrollManagement/:id",
  reports_hr: "/reports_hr",

  //++++++++++ Setup Routes
  goalType: "goalType",
  HRDepartmentSetup: "/HRDepartmentSetup",
  positionType: "/positionType",
  positionLevel: "/positionLevel",
  terminationType: "/terminationType",
  disciplinaryActionType: "/disciplinaryActionType",
  certificationType: "/certificationType",
  qualificationType: "/qualificationType",
  qualificationLevelType: "/qualificationLevelType",
  educationType: "/educationType",
  trainingType: "/trainingType",
  institution: "/institution",
  language: "/language",
  consignmentType: "/consignmentType",
  illnessType: "/illnessType",
  unitOfDuration: "/unitOfDuration",
  nationality: "/nationality",
  employeeStatus: "/employeeStatus",
  leaveType: "/leaveType",

  // hr payroll routes
  payrollRate: "/payrollRate",
  payrollPostingGroup: "/payrollPostingGroup",
  salaryIncomeTax: "/salaryIncomeTax",
  payrollProcess: "/payrollProcess",
};
